name: Check for Duplicate check_uri
on: push

jobs:
  duplicate-url-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Check for duplicate
        run: if [ -n $(grep "check_uri" web_accounts_list.json | cut -f4 -d'"' | uniq -D | head -1) ]; then exit 1; else echo "No duplicates found"; fi
        shell: bash
