name: Check for Duplicate check_uri
on: pull_request

jobs:
  duplicate-url-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Check for duplicate in old JSON
        run: if [ $(grep "check_uri" web_accounts_list.json | cut -f4 -d'"' | uniq -D | head -1) ]; then echo "Found duplicate in web_accounts_list.json!"; exit 1; else echo "No duplicates found"; fi
        shell: bash
      - name: Check for duplicate in new JSON
        run: if [ $(grep "uri_check" wmn-data.json | cut -f4 -d'"' | uniq -D | head -1) ]; then echo "Found duplicate in wmn-data.json!"; exit 1; else echo "No duplicates found"; fi
        shell: bash
