name: Check for Duplicate check_uri
on: push

jobs:
  duplicate-url-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check for duplicate
        run: grep "check_uri" ../../web_accounts_list.json | cut -f4 -d'"' | uniq -D
        shell: bash
